zzhasAd=undefined;document.write("<span id=\"Zedo-Ad=1260992_549_7_300_250;Domain=.zedo.com\"></span>");function getZZPageUrl(){var val='';try{val =(typeof(location.href)=='undefined'?"":escape(location.href));}catch(e){}return val;}function getZZPageRef(){var val='';try{val =(typeof(document.referrer)=='undefined'?"":escape(document.referrer));}catch(e){}return val;}document.write('<script language="JavaScript">'); 
document.write('function google_ad_request_done(google_ads) {'); 
document.write('var s = \'\';'); 
document.write('var i;'); 
document.write('if (google_ads.length == 0) {'); 
document.write('return;'); 
document.write('}'); 
document.write('if (google_ads[0].type == "image") {'); 
document.write('s += \'<a href="\' + google_ads[0].url +'); 
document.write('\'" target="_blank" title="go to \' + google_ads[0].visible_url +'); 
document.write('\'"><img border="0" src="\' + google_ads[0].image_url +'); 
document.write('\'"width="\' + google_ads[0].image_width +'); 
document.write('\'"height="\' + google_ads[0].image_height + \'"></a>\';'); 
document.write('} else if (google_ads[0].type == "flash") {'); 
document.write('s += \'<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"\' +'); 
document.write('\' codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0"\' +'); 
document.write('\' WIDTH="\' + google_ad.image_width +'); 
document.write('\'" HEIGHT="\' + google_ad.image_height + \'">\' +'); 
document.write('\'<PARAM NAME="movie" VALUE="\' + google_ad.image_url + \'">\' +'); 
document.write('\'<PARAM NAME="quality" VALUE="high">\' +'); 
document.write('\'<PARAM NAME="AllowScriptAccess" VALUE="never">\' +'); 
document.write('\'<EMBED src="\' + google_ad.image_url +'); 
document.write('\'" WIDTH="\' + google_ad.image_width +'); 
document.write('\'" HEIGHT="\' + google_ad.image_height +'); 
document.write('\'" TYPE="application/x-shockwave-flash"\' +'); 
document.write('\' AllowScriptAccess="never" \' +'); 
document.write('\' PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer"></EMBED></OBJECT>\';'); 
document.write('}'); 
document.write('else if (google_ads[0].type == "html")'); 
document.write('{'); 
document.write('s += \'<table cellpadding=0 cellspacing=0 border=0 ><tr><td align=center valign=top>\'+ google_ads[0].snippet + \' </td></tr><tr><td align=right>\'+adStr+\'</td></tr></table>\';'); 
document.write('}'); 
document.write('document.write(s);'); 
document.write('return;'); 
document.write('}'); 
document.write('google_ad_client = \'ca-ibnlive_site_js\';;'); 
document.write('google_ad_channel = "ibnlive_backfill_300x250";'); 
document.write('google_ad_output = \'js\';'); 
document.write('google_max_num_ads = \'1\';'); 
document.write('google_ad_type = \'image,flash,html\';'); 
document.write('google_image_size = \'300x250\';'); 
document.write('google_language = \'en\';'); 
document.write('google_encoding = \'utf8\';'); 
document.write('google_safe = \'high\';'); 
document.write('google_page_url=document.location.href;;'); 
document.write('<\/script>'); 
document.write('<script language="JavaScript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">'); 
document.write('<\/script>'); 
