zzhasAd=1;document.write("<span id=\"Zedo-Ad=872782_4_0_300_250;Domain=.zedo.com\"></span>");function getZZPageUrl(){var val='';try{val =(typeof(location.href)=='undefined'?"":escape(location.href));}catch(e){}return val;}function getZZPageRef(){var val='';try{val =(typeof(document.referrer)=='undefined'?"":escape(document.referrer));}catch(e){}return val;}document.write('<script type=\'text/javascript\'>'); 
document.write('var m_u = \'http://www.vizury.com/campaign/showad.php\';'); 
document.write('document.write ("<scr"+"ipt type=\'text/javascript\' src=\'"+m_u);'); 
document.write('document.write ("?width=300");'); 
document.write('document.write ("&amp;height=250");'); 
document.write('document.write ("&amp;publisher_client_id=5555");'); 
document.write('document.write ("&amp;loc=" + escape(window.location));'); 
document.write('if (document.referrer) document.write ("&amp;rfr=" + escape(document.referrer));'); 
document.write('document.write ("\'></scr"+"ipt>");'); 
document.write('<\/script>'); 
