zzhasAd=undefined;document.write("<span id=\"Zedo-Ad=1688821_147_1_300_250;Domain=.zedo.com\"></span>");function getZZPageUrl(){var val='';try{val =(typeof(location.href)=='undefined'?"":escape(location.href));}catch(e){}return val;}function getZZPageRef(){var val='';try{val =(typeof(document.referrer)=='undefined'?"":escape(document.referrer));}catch(e){}return val;}document.write('<script language="JavaScript">'); 
document.write('var google_num_ads = 0;'); 
document.write('var google_last_ad_type = \'\';'); 
document.write('function google_ad_request_done(google_ads) {'); 
document.write('var s;'); 
document.write('if (google_ads.length == 0)'); 
document.write('return;'); 
document.write('google_num_ads += google_ads.length;'); 
document.write('google_last_ad_type = google_ads[0].type;'); 
document.write('s = \'<div class="ad_label"><a class="ad_attribution" href="\'+'); 
document.write('google_info.feedback_url+\'">Ads by Google</a></div>\';'); 
document.write('if (google_ads[0].type == "image") {'); 
document.write('s += \'<a href="\' + google_ads[0].url +'); 
document.write('\'" target="_blank" title="go to \' + google_ads[0].visible_url +'); 
document.write('\'"><img border="0" src="\' + google_ads[0].image_url +'); 
document.write('\'"width="\' + google_ads[0].image_width +'); 
document.write('\'"height="\' + google_ads[0].image_height + \'"></a>\';'); 
document.write('}'); 
document.write('else if (google_ads[0].type == "flash") {'); 
document.write('s += \'<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"\' +'); 
document.write('\' codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,0,0"\' +'); 
document.write('\' WIDTH="\' + google_ad.image_width +'); 
document.write('\'" HEIGHT="\' + google_ad.image_height + \'">\' +'); 
document.write('\'<PARAM NAME="movie" VALUE="\' + google_ad.image_url + \'">\' +'); 
document.write('\'<PARAM NAME="quality" VALUE="high">\' +'); 
document.write('\'<PARAM NAME="AllowScriptAccess" VALUE="never">\' +'); 
document.write('\'<EMBED src="\' + google_ad.image_url +'); 
document.write('\'" WIDTH="\' + google_ad.image_width +'); 
document.write('\'" HEIGHT="\' + google_ad.image_height +'); 
document.write('\'" TYPE="application/x-shockwave-flash"\' +'); 
document.write('\' AllowScriptAccess="never" \' +'); 
document.write('\' PLUGINSPAGE="http://www.macromedia.com/go/getflashplayer"></EMBED></OBJECT>\';'); 
document.write('}'); 
document.write('else if (google_ads[0].type == "html") {'); 
document.write('s += google_ads[0].snippet;'); 
document.write('}'); 
document.write('else if (google_ads[0].type == "text") {'); 
document.write('if (google_ads.length == 1) {'); 
document.write('ad_title_class = \'ad_title_large\';'); 
document.write('ad_text_class = \'ad_text_large\';'); 
document.write('ad_url_class = \'ad_url_large\';'); 
document.write('} else {'); 
document.write('ad_title_class = \'ad_title\';'); 
document.write('ad_text_class = \'ad_text\';'); 
document.write('ad_url_class = \'ad_url\';'); 
document.write('}'); 
document.write('for(var i=0; i < google_ads.length; i++) {'); 
document.write('s += \'<div class="ad_background"><br><a class="\' + ad_title_class + \'" href="\' + google_ads[i].url + \'" >\' +'); 
document.write('google_ads[i].line1 + \'</a><br><span class="\' + ad_text_class + \'">\' +'); 
document.write('google_ads[i].line2 + \' \' +'); 
document.write('google_ads[i].line3 + \'</span><br>\' +'); 
document.write('\'<a class="\' + ad_url_class + \'" href="\' + google_ads[i].url + \'" >\' +'); 
document.write('google_ads[i].visible_url + \'</a><br></div>\';'); 
document.write('}'); 
document.write('}'); 
document.write('document.write(s);'); 
document.write('return;'); 
document.write('}'); 
document.write('<\/script>'); 
document.write('<script language="JavaScript">'); 
document.write('google_ad_client = \'ca-hindu_site_html\';'); 
document.write('google_ad_channel = \'8631795740\';'); 
document.write('google_ad_output = \'js\';'); 
document.write('google_max_num_ads = \'3\';'); 
document.write('google_ad_type = \'image\';'); 
document.write('google_safe = \'high\';'); 
document.write('google_feedback = \'on\';'); 
document.write('google_image_size = \'300x250\';'); 
document.write('<\/script>'); 
document.write('<script language="JavaScript" src="http://pagead2.googlesyndication.com/pagead/show_ads.js">'); 
document.write('<\/script>'); 
